version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./cmd/engine/Dockerfile
    env_file:
      - app.env
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
